services:
  gateway:
    build: 
      context: ./services/gateway
      target: development
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=development
      - USER_SERVICE_URL=http://user-service:3001
      - GAME_SERVICE_URL=http://game-service:3002
      - LOG_SERVICE_URL=http://log-service:3003
    depends_on:
      - user-service
      - game-service
      - log-service
      - database
    volumes:
      - ./services/gateway/src:/app/src
      - shared-data:/app/shared
    command: npm run dev

  user-service:
    build: 
      context: ./services/user-service
      target: development
    ports:
      - "3001:3001"
    environment:
      - NODE_ENV=development
      - DATABASE_URL=sqlite:/app/shared/database/transcendence.db
      - JWT_SECRET=your-secret-key-change-in-production
    depends_on:
      - database
    volumes:
      - ./services/user-service/src:/app/src
      - shared-data:/app/shared
    command: npm run dev

  game-service:
    build: 
      context: ./services/game-service
      target: development
    ports:
      - "3002:3002"
    environment:
      - NODE_ENV=development
      - DATABASE_URL=sqlite:/app/shared/database/transcendence.db
      - USER_SERVICE_URL=http://user-service:3001
    depends_on:
      - database
    volumes:
      - ./services/game-service/src:/app/src
      - shared-data:/app/shared
    command: npm run dev

  log-service:
    build: 
      context: ./services/log-service
      target: development
    ports:
      - "3003:3003"
    environment:
      - NODE_ENV=development
      - DATABASE_URL=sqlite:/app/shared/database/transcendence.db
    volumes:
      - ./services/log-service/src:/app/src
      - shared-data:/app/shared
    command: npm run dev

  frontend:
    build: 
      context: ./frontend
      target: development
    ports:
      - "3004:3004"
    environment:
      - NODE_ENV=development
      - REACT_APP_API_URL=http://localhost:3000
    volumes:
      - ./frontend/src:/app/src
    command: npm run dev

  database:
    image: alpine:latest
    command: sh -c "mkdir -p /shared/database && touch /shared/database/transcendence.db && tail -f /dev/null"
    volumes:
      - shared-data:/shared

volumes:
  shared-data:

networks:
  default:
    name: transcendence-network
